### ISSUE TITLE
[Feature] Allow for multi-line / continuous input into the repl

### ISSUE THREAD

**Issue by jaredpetker** [g0dzill3r/lispy#11]
The mit-scheme (local) repl allows for continous entry into the repl across newline boundaries until the root expression is complete. 

Downloaded mit-scheme for macos from instructions here:
https://groups.csail.mit.edu/mac/users/gjs/6.945/dont-panic/

**Comment by g0dzill3r** [comment]
The real problem is editing the past. You can keep a working buffer and then provide sed-like commands for mutating that state where there are edits to be made.

**Comment by g0dzill3r** [comment]
Check out MultilineTest. It's a single line editor with these commands: 

```
p - print buffer
d - delete last line
c - clear buffer
e - execute buffer
? - show these commands
```

**Comment by g0dzill3r** [comment]
The number of rows in the buffer is in the prompts. And the ":" means it's not a valid expression. A "." means it's valid and ready for execution.
